# Generated by Django 5.2.13 on 2026-04-08 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='performer',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
